"""create obstacles table

Revision ID: 36d3f435847b
Revises: b65e3eb20584
Create Date: 2025-07-20 15:20:11.568730

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "36d3f435847b"
down_revision = "b65e3eb20584"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "obstacles",
        sa.Column("longitude", sa.Integer(), nullable=False, comment="Rover current longitude"),
        sa.Column("latitude", sa.Integer(), nullable=False, comment="Rover current latitude"),
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment='Auto-incrementing unique identifier for each record',
        ),
        sa.Column("create_time", postgresql.TIMESTAMP(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_obstacles_id"), "obstacles", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_obstacles_id"), table_name="obstacles")
    op.drop_table("obstacles")
    # ### end Alembic commands ###
