"""create rover_states_to_command_inputs table

Revision ID: b65e3eb20584
Revises: 985a6ac030dc
Create Date: 2025-07-20 15:18:39.148057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b65e3eb20584"
down_revision = "985a6ac030dc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rover_states_to_command_inputs",
        sa.Column("rover_state_id", sa.Integer(), nullable=False, comment="Rover state ID"),
        sa.Column("command_input_id", sa.Integer(), nullable=False, comment="Command input ID"),
        sa.PrimaryKeyConstraint("rover_state_id", "command_input_id", name="rover_state_id_command_input_id_pkey"),
    )
    op.create_foreign_key(
        "rover_states_to_command_inputs_rover_state_id_fkey",
        "rover_states_to_command_inputs",
        "rover_states",
        ["rover_state_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        "rover_states_to_command_inputs_command_input_id_fkey",
        "rover_states_to_command_inputs",
        "command_inputs",
        ["command_input_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "rover_states_to_command_inputs_command_input_id_fkey", "rover_states_to_command_inputs", type_="foreignkey"
    )
    op.drop_constraint(
        "rover_states_to_command_inputs_rover_state_id_fkey", "rover_states_to_command_inputs", type_="foreignkey"
    )
    op.drop_table("rover_states_to_command_inputs")
    # ### end Alembic commands ###
