"""create rover_states table

Revision ID: 8967d29c5981
Revises: 98f8bb68cc11
Create Date: 2025-07-20 15:14:03.386224

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "8967d29c5981"
down_revision = "98f8bb68cc11"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rover_states",
        sa.Column("longitude", sa.Integer(), nullable=False, comment="Rover current longitude"),
        sa.Column("latitude", sa.Integer(), nullable=False, comment="Rover current latitude"),
        sa.Column(
            "direction",
            sa.Enum("NORTH", "SOUTH", "EAST", "WEST", name="direction_type", create_type=False),
            nullable=False,
            comment="Rover direction",
        ),
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment='Auto-incrementing unique identifier for each record',
        ),
        sa.Column("create_time", postgresql.TIMESTAMP(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_rover_states_id"), "rover_states", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_rover_states_id"), table_name="rover_states")
    op.drop_table("rover_states")
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS direction_type;")
