"""create command_inputs table

Revision ID: 985a6ac030dc
Revises: 8967d29c5981
Create Date: 2025-07-20 15:17:09.453899

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "985a6ac030dc"
down_revision = "8967d29c5981"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "command_inputs",
        sa.Column("command", sa.String(), nullable=False, comment="Inputted command"),
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment='Auto-incrementing unique identifier for each record',
        ),
        sa.Column("create_time", postgresql.TIMESTAMP(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_command_inputs_id"), "command_inputs", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_command_inputs_id"), table_name="command_inputs")
    op.drop_table("command_inputs")
    # ### end Alembic commands ###
