name: FastAPI CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13.5'

    - name: Install dependencies
      run: pip install -r dev-requirements.txt

    - name: Run Ruff Check
      run: ruff check .

    - name: Run Ruff Diff
      run: ruff format . --check --diff

    - name: Run Tests
      run: pytest tests
